<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyPhongGym" Class="QLPhongGymDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI;Initial Catalog=QuanLyPhongGym;Persist Security Info=True;User ID=sa;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="DAMH_Nhom2_QLPhongGym.Properties.Settings" SettingsPropertyName="QuanLyPhongGymConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DatChoLopHoc" Member="DatChoLopHocs">
    <Type Name="DatChoLopHoc">
      <Column Name="DatChoID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KhachHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LichHocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_DatChoLopHoc" Member="KhachHang" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="KhachHang" IsForeignKey="true" />
      <Association Name="LichHoc_DatChoLopHoc" Member="LichHoc" ThisKey="LichHocID" OtherKey="LichHocID" Type="LichHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GoiTap" Member="GoiTaps">
    <Type Name="GoiTap">
      <Column Name="GoiTapID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenGoiTap" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="GoiTap_HoaDon" Member="HoaDons" ThisKey="GoiTapID" OtherKey="GoiTapID" Type="HoaDon" />
      <Association Name="GoiTap_HoiVien" Member="HoiViens" ThisKey="GoiTapID" OtherKey="GoiTapID" Type="HoiVien" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="HoaDonID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KhachHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoiTapID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LoaiHoaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="GoiTap_HoaDon" Member="GoiTap" ThisKey="GoiTapID" OtherKey="GoiTapID" Type="GoiTap" IsForeignKey="true" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoiVien" Member="HoiViens">
    <Type Name="HoiVien">
      <Column Name="HoiVienID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KhachHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GoiTapID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="GoiTap_HoiVien" Member="GoiTap" ThisKey="GoiTapID" OtherKey="GoiTapID" Type="GoiTap" IsForeignKey="true" />
      <Association Name="KhachHang_HoiVien" Member="KhachHang" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HuanLuyenVien" Member="HuanLuyenViens">
    <Type Name="HuanLuyenVien">
      <Column Name="HLV_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChuyenMon" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NhanVienID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HuanLuyenVien_LichHoc" Member="LichHocs" ThisKey="HLV_ID" OtherKey="HLV_ID" Type="LichHoc" />
      <Association Name="NhanVien_HuanLuyenVien" Member="NhanVien" ThisKey="NhanVienID" OtherKey="NhanVienID" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="KhachHangID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LoaiKhachHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_DatChoLopHoc" Member="DatChoLopHocs" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="DatChoLopHoc" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="HoaDon" />
      <Association Name="KhachHang_HoiVien" Member="HoiViens" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="HoiVien" />
      <Association Name="KhachHang_PhanHoi" Member="PhanHois" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="PhanHoi" />
      <Association Name="KhachHang_SuDungThietBi" Member="SuDungThietBis" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="SuDungThietBi" />
      <Association Name="LoaiKhachHang_KhachHang" Member="LoaiKhachHang" ThisKey="LoaiKhachHangID" OtherKey="LoaiKhachHangID" Type="LoaiKhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichHoc" Member="LichHocs">
    <Type Name="LichHoc">
      <Column Name="LichHocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LopHocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HLV_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayHoc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianBatDau" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianKetThuc" Type="System.TimeSpan" DbType="Time NOT NULL" CanBeNull="false" />
      <Association Name="LichHoc_DatChoLopHoc" Member="DatChoLopHocs" ThisKey="LichHocID" OtherKey="LichHocID" Type="DatChoLopHoc" />
      <Association Name="HuanLuyenVien_LichHoc" Member="HuanLuyenVien" ThisKey="HLV_ID" OtherKey="HLV_ID" Type="HuanLuyenVien" IsForeignKey="true" />
      <Association Name="LopHoc_LichHoc" Member="LopHoc" ThisKey="LopHocID" OtherKey="LopHocID" Type="LopHoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuBaoTri" Member="LichSuBaoTris">
    <Type Name="LichSuBaoTri">
      <Column Name="BaoTriID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThietBiID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayBaoTri" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ThietBi_LichSuBaoTri" Member="ThietBi" ThisKey="ThietBiID" OtherKey="ThietBiID" Type="ThietBi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiKhachHang" Member="LoaiKhachHangs">
    <Type Name="LoaiKhachHang">
      <Column Name="LoaiKhachHangID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="LoaiKhachHang_KhachHang" Member="KhachHangs" ThisKey="LoaiKhachHangID" OtherKey="LoaiKhachHangID" Type="KhachHang" />
    </Type>
  </Table>
  <Table Name="dbo.LopHoc" Member="LopHocs">
    <Type Name="LopHoc">
      <Column Name="LopHocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLop" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="LopHoc_LichHoc" Member="LichHocs" ThisKey="LopHocID" OtherKey="LopHocID" Type="LichHoc" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="NhanVienID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_HuanLuyenVien" Member="HuanLuyenViens" ThisKey="NhanVienID" OtherKey="NhanVienID" Type="HuanLuyenVien" />
    </Type>
  </Table>
  <Table Name="dbo.PhongTap" Member="PhongTaps">
    <Type Name="PhongTap">
      <Column Name="PhongTapID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhong" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PhanHoi" Member="PhanHois">
    <Type Name="PhanHoi">
      <Column Name="PhanHoiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KhachHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgayPhanHoi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_PhanHoi" Member="KhachHang" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SuDungThietBi" Member="SuDungThietBis">
    <Type Name="SuDungThietBi">
      <Column Name="SuDungID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KhachHangID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThietBiID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianBatDau" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhachHang_SuDungThietBi" Member="KhachHang" ThisKey="KhachHangID" OtherKey="KhachHangID" Type="KhachHang" IsForeignKey="true" />
      <Association Name="ThietBi_SuDungThietBi" Member="ThietBi" ThisKey="ThietBiID" OtherKey="ThietBiID" Type="ThietBi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThietBi" Member="ThietBis">
    <Type Name="ThietBi">
      <Column Name="ThietBiID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenThietBi" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="ThietBi_LichSuBaoTri" Member="LichSuBaoTris" ThisKey="ThietBiID" OtherKey="ThietBiID" Type="LichSuBaoTri" />
      <Association Name="ThietBi_SuDungThietBi" Member="SuDungThietBis" ThisKey="ThietBiID" OtherKey="ThietBiID" Type="SuDungThietBi" />
    </Type>
  </Table>
</Database>