#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAMH_Nhom2_QLPhongGym
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLPhongGym")]
	public partial class QLPhongGymDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiNhanh(ChiNhanh instance);
    partial void UpdateChiNhanh(ChiNhanh instance);
    partial void DeleteChiNhanh(ChiNhanh instance);
    partial void InsertDangKyLichTap(DangKyLichTap instance);
    partial void UpdateDangKyLichTap(DangKyLichTap instance);
    partial void DeleteDangKyLichTap(DangKyLichTap instance);
    partial void InsertGoiTap(GoiTap instance);
    partial void UpdateGoiTap(GoiTap instance);
    partial void DeleteGoiTap(GoiTap instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertHuanLuyenVien(HuanLuyenVien instance);
    partial void UpdateHuanLuyenVien(HuanLuyenVien instance);
    partial void DeleteHuanLuyenVien(HuanLuyenVien instance);
    partial void InsertLichSuBaoTri(LichSuBaoTri instance);
    partial void UpdateLichSuBaoTri(LichSuBaoTri instance);
    partial void DeleteLichSuBaoTri(LichSuBaoTri instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertLichTap(LichTap instance);
    partial void UpdateLichTap(LichTap instance);
    partial void DeleteLichTap(LichTap instance);
    partial void InsertSuDungThietBi(SuDungThietBi instance);
    partial void UpdateSuDungThietBi(SuDungThietBi instance);
    partial void DeleteSuDungThietBi(SuDungThietBi instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertTheKhachHang(TheKhachHang instance);
    partial void UpdateTheKhachHang(TheKhachHang instance);
    partial void DeleteTheKhachHang(TheKhachHang instance);
    partial void InsertThietBi(ThietBi instance);
    partial void UpdateThietBi(ThietBi instance);
    partial void DeleteThietBi(ThietBi instance);
    partial void InsertThuePT(ThuePT instance);
    partial void UpdateThuePT(ThuePT instance);
    partial void DeleteThuePT(ThuePT instance);
    #endregion
		
		public QLPhongGymDataContext() : 
				base(global::DAMH_Nhom2_QLPhongGym.Properties.Settings.Default.QLPhongGymConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public QLPhongGymDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPhongGymDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPhongGymDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLPhongGymDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiNhanh> ChiNhanhs
		{
			get
			{
				return this.GetTable<ChiNhanh>();
			}
		}
		
		public System.Data.Linq.Table<DangKyLichTap> DangKyLichTaps
		{
			get
			{
				return this.GetTable<DangKyLichTap>();
			}
		}
		
		public System.Data.Linq.Table<GoiTap> GoiTaps
		{
			get
			{
				return this.GetTable<GoiTap>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<HuanLuyenVien> HuanLuyenViens
		{
			get
			{
				return this.GetTable<HuanLuyenVien>();
			}
		}
		
		public System.Data.Linq.Table<LichSuBaoTri> LichSuBaoTris
		{
			get
			{
				return this.GetTable<LichSuBaoTri>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<LichTap> LichTaps
		{
			get
			{
				return this.GetTable<LichTap>();
			}
		}
		
		public System.Data.Linq.Table<SuDungThietBi> SuDungThietBis
		{
			get
			{
				return this.GetTable<SuDungThietBi>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<TheKhachHang> TheKhachHangs
		{
			get
			{
				return this.GetTable<TheKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<ThietBi> ThietBis
		{
			get
			{
				return this.GetTable<ThietBi>();
			}
		}
		
		public System.Data.Linq.Table<ThuePT> ThuePTs
		{
			get
			{
				return this.GetTable<ThuePT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiNhanh")]
	public partial class ChiNhanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChiNhanhID;
		
		private string _TenDiaDiem;
		
		private string _DiaDiem;
		
		private string _MoTa;
		
		private EntitySet<LichTap> _LichTaps;
		
		private EntitySet<ThietBi> _ThietBis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChiNhanhIDChanging(int value);
    partial void OnChiNhanhIDChanged();
    partial void OnTenDiaDiemChanging(string value);
    partial void OnTenDiaDiemChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public ChiNhanh()
		{
			this._LichTaps = new EntitySet<LichTap>(new Action<LichTap>(this.attach_LichTaps), new Action<LichTap>(this.detach_LichTaps));
			this._ThietBis = new EntitySet<ThietBi>(new Action<ThietBi>(this.attach_ThietBis), new Action<ThietBi>(this.detach_ThietBis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiNhanhID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ChiNhanhID
		{
			get
			{
				return this._ChiNhanhID;
			}
			set
			{
				if ((this._ChiNhanhID != value))
				{
					this.OnChiNhanhIDChanging(value);
					this.SendPropertyChanging();
					this._ChiNhanhID = value;
					this.SendPropertyChanged("ChiNhanhID");
					this.OnChiNhanhIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDiem", DbType="NVarChar(100)")]
		public string TenDiaDiem
		{
			get
			{
				return this._TenDiaDiem;
			}
			set
			{
				if ((this._TenDiaDiem != value))
				{
					this.OnTenDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDiem = value;
					this.SendPropertyChanged("TenDiaDiem");
					this.OnTenDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(100)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(255)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_LichTap", Storage="_LichTaps", ThisKey="ChiNhanhID", OtherKey="ChiNhanhID")]
		public EntitySet<LichTap> LichTaps
		{
			get
			{
				return this._LichTaps;
			}
			set
			{
				this._LichTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_ThietBi", Storage="_ThietBis", ThisKey="ChiNhanhID", OtherKey="ChiNhanhID")]
		public EntitySet<ThietBi> ThietBis
		{
			get
			{
				return this._ThietBis;
			}
			set
			{
				this._ThietBis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTaps(LichTap entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = this;
		}
		
		private void detach_LichTaps(LichTap entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = null;
		}
		
		private void attach_ThietBis(ThietBi entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = this;
		}
		
		private void detach_ThietBis(ThietBi entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangKyLichTap")]
	public partial class DangKyLichTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DangKyHLV_ID;
		
		private System.Nullable<int> _TheKhachHangID;
		
		private System.Nullable<int> _LichTapID;
		
		private EntityRef<LichTap> _LichTap;
		
		private EntityRef<TheKhachHang> _TheKhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDangKyHLV_IDChanging(int value);
    partial void OnDangKyHLV_IDChanged();
    partial void OnTheKhachHangIDChanging(System.Nullable<int> value);
    partial void OnTheKhachHangIDChanged();
    partial void OnLichTapIDChanging(System.Nullable<int> value);
    partial void OnLichTapIDChanged();
    #endregion
		
		public DangKyLichTap()
		{
			this._LichTap = default(EntityRef<LichTap>);
			this._TheKhachHang = default(EntityRef<TheKhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangKyHLV_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DangKyHLV_ID
		{
			get
			{
				return this._DangKyHLV_ID;
			}
			set
			{
				if ((this._DangKyHLV_ID != value))
				{
					this.OnDangKyHLV_IDChanging(value);
					this.SendPropertyChanging();
					this._DangKyHLV_ID = value;
					this.SendPropertyChanged("DangKyHLV_ID");
					this.OnDangKyHLV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheKhachHangID", DbType="Int")]
		public System.Nullable<int> TheKhachHangID
		{
			get
			{
				return this._TheKhachHangID;
			}
			set
			{
				if ((this._TheKhachHangID != value))
				{
					if (this._TheKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTheKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._TheKhachHangID = value;
					this.SendPropertyChanged("TheKhachHangID");
					this.OnTheKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LichTapID", DbType="Int")]
		public System.Nullable<int> LichTapID
		{
			get
			{
				return this._LichTapID;
			}
			set
			{
				if ((this._LichTapID != value))
				{
					if (this._LichTap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLichTapIDChanging(value);
					this.SendPropertyChanging();
					this._LichTapID = value;
					this.SendPropertyChanged("LichTapID");
					this.OnLichTapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTap_DangKyLichTap", Storage="_LichTap", ThisKey="LichTapID", OtherKey="LichTapID", IsForeignKey=true)]
		public LichTap LichTap
		{
			get
			{
				return this._LichTap.Entity;
			}
			set
			{
				LichTap previousValue = this._LichTap.Entity;
				if (((previousValue != value) 
							|| (this._LichTap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTap.Entity = null;
						previousValue.DangKyLichTaps.Remove(this);
					}
					this._LichTap.Entity = value;
					if ((value != null))
					{
						value.DangKyLichTaps.Add(this);
						this._LichTapID = value.LichTapID;
					}
					else
					{
						this._LichTapID = default(Nullable<int>);
					}
					this.SendPropertyChanged("LichTap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheKhachHang_DangKyLichTap", Storage="_TheKhachHang", ThisKey="TheKhachHangID", OtherKey="TheKhachHangID", IsForeignKey=true)]
		public TheKhachHang TheKhachHang
		{
			get
			{
				return this._TheKhachHang.Entity;
			}
			set
			{
				TheKhachHang previousValue = this._TheKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._TheKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheKhachHang.Entity = null;
						previousValue.DangKyLichTaps.Remove(this);
					}
					this._TheKhachHang.Entity = value;
					if ((value != null))
					{
						value.DangKyLichTaps.Add(this);
						this._TheKhachHangID = value.TheKhachHangID;
					}
					else
					{
						this._TheKhachHangID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TheKhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GoiTap")]
	public partial class GoiTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GoiTapID;
		
		private System.Nullable<int> _ThoiGian;
		
		private System.Nullable<decimal> _GiaTien;
		
		private string _Mota;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGoiTapIDChanging(int value);
    partial void OnGoiTapIDChanged();
    partial void OnThoiGianChanging(System.Nullable<int> value);
    partial void OnThoiGianChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public GoiTap()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoiTapID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GoiTapID
		{
			get
			{
				return this._GoiTapID;
			}
			set
			{
				if ((this._GoiTapID != value))
				{
					this.OnGoiTapIDChanging(value);
					this.SendPropertyChanging();
					this._GoiTapID = value;
					this.SendPropertyChanged("GoiTapID");
					this.OnGoiTapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="Int")]
		public System.Nullable<int> ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(100)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GoiTap_HoaDon", Storage="_HoaDons", ThisKey="GoiTapID", OtherKey="GoiTapID")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.GoiTap = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.GoiTap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HoaDonID;
		
		private System.Nullable<int> _TheKhachHangID;
		
		private System.Nullable<int> _NhanVienID;
		
		private System.Nullable<System.DateTime> _NgayThanhToan;
		
		private string _LoaiHoaDon;
		
		private System.Nullable<int> _GoiTapID;
		
		private System.Nullable<int> _GoiThuePTID;
		
		private System.Nullable<decimal> _TongTien;
		
		private EntityRef<GoiTap> _GoiTap;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<TheKhachHang> _TheKhachHang;
		
		private EntityRef<ThuePT> _ThuePT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHoaDonIDChanging(int value);
    partial void OnHoaDonIDChanged();
    partial void OnTheKhachHangIDChanging(System.Nullable<int> value);
    partial void OnTheKhachHangIDChanged();
    partial void OnNhanVienIDChanging(System.Nullable<int> value);
    partial void OnNhanVienIDChanged();
    partial void OnNgayThanhToanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayThanhToanChanged();
    partial void OnLoaiHoaDonChanging(string value);
    partial void OnLoaiHoaDonChanged();
    partial void OnGoiTapIDChanging(System.Nullable<int> value);
    partial void OnGoiTapIDChanged();
    partial void OnGoiThuePTIDChanging(System.Nullable<int> value);
    partial void OnGoiThuePTIDChanged();
    partial void OnTongTienChanging(System.Nullable<decimal> value);
    partial void OnTongTienChanged();
    #endregion
		
		public HoaDon()
		{
			this._GoiTap = default(EntityRef<GoiTap>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._TheKhachHang = default(EntityRef<TheKhachHang>);
			this._ThuePT = default(EntityRef<ThuePT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoaDonID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HoaDonID
		{
			get
			{
				return this._HoaDonID;
			}
			set
			{
				if ((this._HoaDonID != value))
				{
					this.OnHoaDonIDChanging(value);
					this.SendPropertyChanging();
					this._HoaDonID = value;
					this.SendPropertyChanged("HoaDonID");
					this.OnHoaDonIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheKhachHangID", DbType="Int")]
		public System.Nullable<int> TheKhachHangID
		{
			get
			{
				return this._TheKhachHangID;
			}
			set
			{
				if ((this._TheKhachHangID != value))
				{
					if (this._TheKhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTheKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._TheKhachHangID = value;
					this.SendPropertyChanged("TheKhachHangID");
					this.OnTheKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="Int")]
		public System.Nullable<int> NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayThanhToan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayThanhToan
		{
			get
			{
				return this._NgayThanhToan;
			}
			set
			{
				if ((this._NgayThanhToan != value))
				{
					this.OnNgayThanhToanChanging(value);
					this.SendPropertyChanging();
					this._NgayThanhToan = value;
					this.SendPropertyChanged("NgayThanhToan");
					this.OnNgayThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHoaDon", DbType="NVarChar(100)")]
		public string LoaiHoaDon
		{
			get
			{
				return this._LoaiHoaDon;
			}
			set
			{
				if ((this._LoaiHoaDon != value))
				{
					this.OnLoaiHoaDonChanging(value);
					this.SendPropertyChanging();
					this._LoaiHoaDon = value;
					this.SendPropertyChanged("LoaiHoaDon");
					this.OnLoaiHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoiTapID", DbType="Int")]
		public System.Nullable<int> GoiTapID
		{
			get
			{
				return this._GoiTapID;
			}
			set
			{
				if ((this._GoiTapID != value))
				{
					if (this._GoiTap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGoiTapIDChanging(value);
					this.SendPropertyChanging();
					this._GoiTapID = value;
					this.SendPropertyChanged("GoiTapID");
					this.OnGoiTapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoiThuePTID", DbType="Int")]
		public System.Nullable<int> GoiThuePTID
		{
			get
			{
				return this._GoiThuePTID;
			}
			set
			{
				if ((this._GoiThuePTID != value))
				{
					if (this._ThuePT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGoiThuePTIDChanging(value);
					this.SendPropertyChanging();
					this._GoiThuePTID = value;
					this.SendPropertyChanged("GoiThuePTID");
					this.OnGoiThuePTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GoiTap_HoaDon", Storage="_GoiTap", ThisKey="GoiTapID", OtherKey="GoiTapID", IsForeignKey=true)]
		public GoiTap GoiTap
		{
			get
			{
				return this._GoiTap.Entity;
			}
			set
			{
				GoiTap previousValue = this._GoiTap.Entity;
				if (((previousValue != value) 
							|| (this._GoiTap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GoiTap.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._GoiTap.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._GoiTapID = value.GoiTapID;
					}
					else
					{
						this._GoiTapID = default(Nullable<int>);
					}
					this.SendPropertyChanged("GoiTap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="NhanVienID", OtherKey="NhanVienID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._NhanVienID = value.NhanVienID;
					}
					else
					{
						this._NhanVienID = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheKhachHang_HoaDon", Storage="_TheKhachHang", ThisKey="TheKhachHangID", OtherKey="TheKhachHangID", IsForeignKey=true)]
		public TheKhachHang TheKhachHang
		{
			get
			{
				return this._TheKhachHang.Entity;
			}
			set
			{
				TheKhachHang previousValue = this._TheKhachHang.Entity;
				if (((previousValue != value) 
							|| (this._TheKhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TheKhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._TheKhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._TheKhachHangID = value.TheKhachHangID;
					}
					else
					{
						this._TheKhachHangID = default(Nullable<int>);
					}
					this.SendPropertyChanged("TheKhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuePT_HoaDon", Storage="_ThuePT", ThisKey="GoiThuePTID", OtherKey="GoiThuePTID", IsForeignKey=true)]
		public ThuePT ThuePT
		{
			get
			{
				return this._ThuePT.Entity;
			}
			set
			{
				ThuePT previousValue = this._ThuePT.Entity;
				if (((previousValue != value) 
							|| (this._ThuePT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThuePT.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._ThuePT.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._GoiThuePTID = value.GoiThuePTID;
					}
					else
					{
						this._GoiThuePTID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThuePT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HuanLuyenVien")]
	public partial class HuanLuyenVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HLV_ID;
		
		private System.Nullable<int> _NhanVienID;
		
		private string _HoTen;
		
		private string _ChuyenMon;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private EntitySet<LichTap> _LichTaps;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHLV_IDChanging(int value);
    partial void OnHLV_IDChanged();
    partial void OnNhanVienIDChanging(System.Nullable<int> value);
    partial void OnNhanVienIDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnChuyenMonChanging(string value);
    partial void OnChuyenMonChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public HuanLuyenVien()
		{
			this._LichTaps = new EntitySet<LichTap>(new Action<LichTap>(this.attach_LichTaps), new Action<LichTap>(this.detach_LichTaps));
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLV_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HLV_ID
		{
			get
			{
				return this._HLV_ID;
			}
			set
			{
				if ((this._HLV_ID != value))
				{
					this.OnHLV_IDChanging(value);
					this.SendPropertyChanging();
					this._HLV_ID = value;
					this.SendPropertyChanged("HLV_ID");
					this.OnHLV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="Int")]
		public System.Nullable<int> NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuyenMon", DbType="NVarChar(100)")]
		public string ChuyenMon
		{
			get
			{
				return this._ChuyenMon;
			}
			set
			{
				if ((this._ChuyenMon != value))
				{
					this.OnChuyenMonChanging(value);
					this.SendPropertyChanging();
					this._ChuyenMon = value;
					this.SendPropertyChanged("ChuyenMon");
					this.OnChuyenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HuanLuyenVien_LichTap", Storage="_LichTaps", ThisKey="HLV_ID", OtherKey="HLV_ID")]
		public EntitySet<LichTap> LichTaps
		{
			get
			{
				return this._LichTaps;
			}
			set
			{
				this._LichTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HuanLuyenVien", Storage="_NhanVien", ThisKey="NhanVienID", OtherKey="NhanVienID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HuanLuyenViens.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HuanLuyenViens.Add(this);
						this._NhanVienID = value.NhanVienID;
					}
					else
					{
						this._NhanVienID = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTaps(LichTap entity)
		{
			this.SendPropertyChanging();
			entity.HuanLuyenVien = this;
		}
		
		private void detach_LichTaps(LichTap entity)
		{
			this.SendPropertyChanging();
			entity.HuanLuyenVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuBaoTri")]
	public partial class LichSuBaoTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BaoTriID;
		
		private System.Nullable<int> _ThietBiID;
		
		private System.Nullable<System.DateTime> _NgayBaoTri;
		
		private string _MoTa;
		
		private EntityRef<ThietBi> _ThietBi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBaoTriIDChanging(int value);
    partial void OnBaoTriIDChanged();
    partial void OnThietBiIDChanging(System.Nullable<int> value);
    partial void OnThietBiIDChanged();
    partial void OnNgayBaoTriChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBaoTriChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    #endregion
		
		public LichSuBaoTri()
		{
			this._ThietBi = default(EntityRef<ThietBi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaoTriID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BaoTriID
		{
			get
			{
				return this._BaoTriID;
			}
			set
			{
				if ((this._BaoTriID != value))
				{
					this.OnBaoTriIDChanging(value);
					this.SendPropertyChanging();
					this._BaoTriID = value;
					this.SendPropertyChanged("BaoTriID");
					this.OnBaoTriIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiID", DbType="Int")]
		public System.Nullable<int> ThietBiID
		{
			get
			{
				return this._ThietBiID;
			}
			set
			{
				if ((this._ThietBiID != value))
				{
					if (this._ThietBi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnThietBiIDChanging(value);
					this.SendPropertyChanging();
					this._ThietBiID = value;
					this.SendPropertyChanged("ThietBiID");
					this.OnThietBiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBaoTri", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBaoTri
		{
			get
			{
				return this._NgayBaoTri;
			}
			set
			{
				if ((this._NgayBaoTri != value))
				{
					this.OnNgayBaoTriChanging(value);
					this.SendPropertyChanging();
					this._NgayBaoTri = value;
					this.SendPropertyChanged("NgayBaoTri");
					this.OnNgayBaoTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(255)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_LichSuBaoTri", Storage="_ThietBi", ThisKey="ThietBiID", OtherKey="ThietBiID", IsForeignKey=true)]
		public ThietBi ThietBi
		{
			get
			{
				return this._ThietBi.Entity;
			}
			set
			{
				ThietBi previousValue = this._ThietBi.Entity;
				if (((previousValue != value) 
							|| (this._ThietBi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThietBi.Entity = null;
						previousValue.LichSuBaoTris.Remove(this);
					}
					this._ThietBi.Entity = value;
					if ((value != null))
					{
						value.LichSuBaoTris.Add(this);
						this._ThietBiID = value.ThietBiID;
					}
					else
					{
						this._ThietBiID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThietBi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NhanVienID;
		
		private string _HoTen;
		
		private string _ChucVu;
		
		private string _SoDienThoai;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _NgayVaoLam;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntitySet<HuanLuyenVien> _HuanLuyenViens;
		
		private EntitySet<TaiKhoan> _TaiKhoans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNhanVienIDChanging(int value);
    partial void OnNhanVienIDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgayVaoLamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoLamChanged();
    #endregion
		
		public NhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._HuanLuyenViens = new EntitySet<HuanLuyenVien>(new Action<HuanLuyenVien>(this.attach_HuanLuyenViens), new Action<HuanLuyenVien>(this.detach_HuanLuyenViens));
			this._TaiKhoans = new EntitySet<TaiKhoan>(new Action<TaiKhoan>(this.attach_TaiKhoans), new Action<TaiKhoan>(this.detach_TaiKhoans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(50)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoLam", DbType="Date")]
		public System.Nullable<System.DateTime> NgayVaoLam
		{
			get
			{
				return this._NgayVaoLam;
			}
			set
			{
				if ((this._NgayVaoLam != value))
				{
					this.OnNgayVaoLamChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoLam = value;
					this.SendPropertyChanged("NgayVaoLam");
					this.OnNgayVaoLamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="NhanVienID", OtherKey="NhanVienID")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HuanLuyenVien", Storage="_HuanLuyenViens", ThisKey="NhanVienID", OtherKey="NhanVienID")]
		public EntitySet<HuanLuyenVien> HuanLuyenViens
		{
			get
			{
				return this._HuanLuyenViens;
			}
			set
			{
				this._HuanLuyenViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_TaiKhoans", ThisKey="NhanVienID", OtherKey="NhanVienID")]
		public EntitySet<TaiKhoan> TaiKhoans
		{
			get
			{
				return this._TaiKhoans;
			}
			set
			{
				this._TaiKhoans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HuanLuyenViens(HuanLuyenVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HuanLuyenViens(HuanLuyenVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_TaiKhoans(TaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichTap")]
	public partial class LichTap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LichTapID;
		
		private System.Nullable<int> _HLV_ID;
		
		private System.Nullable<int> _ChiNhanhID;
		
		private System.Nullable<System.TimeSpan> _ThoiGianBatDau;
		
		private System.Nullable<System.TimeSpan> _ThoiGianKetThuc;
		
		private System.Nullable<System.DateTime> _NgayBatDau;
		
		private string _TrangThai;
		
		private EntitySet<DangKyLichTap> _DangKyLichTaps;
		
		private EntityRef<ChiNhanh> _ChiNhanh;
		
		private EntityRef<HuanLuyenVien> _HuanLuyenVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLichTapIDChanging(int value);
    partial void OnLichTapIDChanged();
    partial void OnHLV_IDChanging(System.Nullable<int> value);
    partial void OnHLV_IDChanged();
    partial void OnChiNhanhIDChanging(System.Nullable<int> value);
    partial void OnChiNhanhIDChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.TimeSpan> value);
    partial void OnThoiGianKetThucChanged();
    partial void OnNgayBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public LichTap()
		{
			this._DangKyLichTaps = new EntitySet<DangKyLichTap>(new Action<DangKyLichTap>(this.attach_DangKyLichTaps), new Action<DangKyLichTap>(this.detach_DangKyLichTaps));
			this._ChiNhanh = default(EntityRef<ChiNhanh>);
			this._HuanLuyenVien = default(EntityRef<HuanLuyenVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LichTapID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LichTapID
		{
			get
			{
				return this._LichTapID;
			}
			set
			{
				if ((this._LichTapID != value))
				{
					this.OnLichTapIDChanging(value);
					this.SendPropertyChanging();
					this._LichTapID = value;
					this.SendPropertyChanged("LichTapID");
					this.OnLichTapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HLV_ID", DbType="Int")]
		public System.Nullable<int> HLV_ID
		{
			get
			{
				return this._HLV_ID;
			}
			set
			{
				if ((this._HLV_ID != value))
				{
					if (this._HuanLuyenVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHLV_IDChanging(value);
					this.SendPropertyChanging();
					this._HLV_ID = value;
					this.SendPropertyChanged("HLV_ID");
					this.OnHLV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiNhanhID", DbType="Int")]
		public System.Nullable<int> ChiNhanhID
		{
			get
			{
				return this._ChiNhanhID;
			}
			set
			{
				if ((this._ChiNhanhID != value))
				{
					if (this._ChiNhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChiNhanhIDChanging(value);
					this.SendPropertyChanging();
					this._ChiNhanhID = value;
					this.SendPropertyChanged("ChiNhanhID");
					this.OnChiNhanhIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTap_DangKyLichTap", Storage="_DangKyLichTaps", ThisKey="LichTapID", OtherKey="LichTapID")]
		public EntitySet<DangKyLichTap> DangKyLichTaps
		{
			get
			{
				return this._DangKyLichTaps;
			}
			set
			{
				this._DangKyLichTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_LichTap", Storage="_ChiNhanh", ThisKey="ChiNhanhID", OtherKey="ChiNhanhID", IsForeignKey=true)]
		public ChiNhanh ChiNhanh
		{
			get
			{
				return this._ChiNhanh.Entity;
			}
			set
			{
				ChiNhanh previousValue = this._ChiNhanh.Entity;
				if (((previousValue != value) 
							|| (this._ChiNhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiNhanh.Entity = null;
						previousValue.LichTaps.Remove(this);
					}
					this._ChiNhanh.Entity = value;
					if ((value != null))
					{
						value.LichTaps.Add(this);
						this._ChiNhanhID = value.ChiNhanhID;
					}
					else
					{
						this._ChiNhanhID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChiNhanh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HuanLuyenVien_LichTap", Storage="_HuanLuyenVien", ThisKey="HLV_ID", OtherKey="HLV_ID", IsForeignKey=true)]
		public HuanLuyenVien HuanLuyenVien
		{
			get
			{
				return this._HuanLuyenVien.Entity;
			}
			set
			{
				HuanLuyenVien previousValue = this._HuanLuyenVien.Entity;
				if (((previousValue != value) 
							|| (this._HuanLuyenVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HuanLuyenVien.Entity = null;
						previousValue.LichTaps.Remove(this);
					}
					this._HuanLuyenVien.Entity = value;
					if ((value != null))
					{
						value.LichTaps.Add(this);
						this._HLV_ID = value.HLV_ID;
					}
					else
					{
						this._HLV_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("HuanLuyenVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyLichTaps(DangKyLichTap entity)
		{
			this.SendPropertyChanging();
			entity.LichTap = this;
		}
		
		private void detach_DangKyLichTaps(DangKyLichTap entity)
		{
			this.SendPropertyChanging();
			entity.LichTap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SuDungThietBi")]
	public partial class SuDungThietBi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SuDungID;
		
		private System.Nullable<int> _ThietBiID;
		
		private System.Nullable<System.DateTime> _ThoiGianBatDau;
		
		private System.Nullable<System.DateTime> _ThoiGianKetThuc;
		
		private EntityRef<ThietBi> _ThietBi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSuDungIDChanging(int value);
    partial void OnSuDungIDChanged();
    partial void OnThietBiIDChanging(System.Nullable<int> value);
    partial void OnThietBiIDChanged();
    partial void OnThoiGianBatDauChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianBatDauChanged();
    partial void OnThoiGianKetThucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianKetThucChanged();
    #endregion
		
		public SuDungThietBi()
		{
			this._ThietBi = default(EntityRef<ThietBi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SuDungID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SuDungID
		{
			get
			{
				return this._SuDungID;
			}
			set
			{
				if ((this._SuDungID != value))
				{
					this.OnSuDungIDChanging(value);
					this.SendPropertyChanging();
					this._SuDungID = value;
					this.SendPropertyChanged("SuDungID");
					this.OnSuDungIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiID", DbType="Int")]
		public System.Nullable<int> ThietBiID
		{
			get
			{
				return this._ThietBiID;
			}
			set
			{
				if ((this._ThietBiID != value))
				{
					if (this._ThietBi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnThietBiIDChanging(value);
					this.SendPropertyChanging();
					this._ThietBiID = value;
					this.SendPropertyChanged("ThietBiID");
					this.OnThietBiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianBatDau", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianBatDau
		{
			get
			{
				return this._ThoiGianBatDau;
			}
			set
			{
				if ((this._ThoiGianBatDau != value))
				{
					this.OnThoiGianBatDauChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianBatDau = value;
					this.SendPropertyChanged("ThoiGianBatDau");
					this.OnThoiGianBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianKetThuc", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianKetThuc
		{
			get
			{
				return this._ThoiGianKetThuc;
			}
			set
			{
				if ((this._ThoiGianKetThuc != value))
				{
					this.OnThoiGianKetThucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianKetThuc = value;
					this.SendPropertyChanged("ThoiGianKetThuc");
					this.OnThoiGianKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_SuDungThietBi", Storage="_ThietBi", ThisKey="ThietBiID", OtherKey="ThietBiID", IsForeignKey=true)]
		public ThietBi ThietBi
		{
			get
			{
				return this._ThietBi.Entity;
			}
			set
			{
				ThietBi previousValue = this._ThietBi.Entity;
				if (((previousValue != value) 
							|| (this._ThietBi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThietBi.Entity = null;
						previousValue.SuDungThietBis.Remove(this);
					}
					this._ThietBi.Entity = value;
					if ((value != null))
					{
						value.SuDungThietBis.Add(this);
						this._ThietBiID = value.ThietBiID;
					}
					else
					{
						this._ThietBiID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ThietBi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TaiKhoanID;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private System.Nullable<int> _NhanVienID;
		
		private string _Quyen;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTaiKhoanIDChanging(int value);
    partial void OnTaiKhoanIDChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnNhanVienIDChanging(System.Nullable<int> value);
    partial void OnNhanVienIDChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TaiKhoanID
		{
			get
			{
				return this._TaiKhoanID;
			}
			set
			{
				if ((this._TaiKhoanID != value))
				{
					this.OnTaiKhoanIDChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoanID = value;
					this.SendPropertyChanged("TaiKhoanID");
					this.OnTaiKhoanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanVienID", DbType="Int")]
		public System.Nullable<int> NhanVienID
		{
			get
			{
				return this._NhanVienID;
			}
			set
			{
				if ((this._NhanVienID != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNhanVienIDChanging(value);
					this.SendPropertyChanging();
					this._NhanVienID = value;
					this.SendPropertyChanged("NhanVienID");
					this.OnNhanVienIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_TaiKhoan", Storage="_NhanVien", ThisKey="NhanVienID", OtherKey="NhanVienID", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoans.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoans.Add(this);
						this._NhanVienID = value.NhanVienID;
					}
					else
					{
						this._NhanVienID = default(Nullable<int>);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TheKhachHang")]
	public partial class TheKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TheKhachHangID;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _CCCD;
		
		private string _GioiTinh;
		
		private string _SoDienThoai;
		
		private string _DiaChi;
		
		private string _LoaiThanhVien;
		
		private System.Nullable<System.DateTime> _ThoiGianHieuLuc;
		
		private System.Nullable<int> _SoBuoiTapCungPT;
		
		private EntitySet<DangKyLichTap> _DangKyLichTaps;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTheKhachHangIDChanging(int value);
    partial void OnTheKhachHangIDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnLoaiThanhVienChanging(string value);
    partial void OnLoaiThanhVienChanged();
    partial void OnThoiGianHieuLucChanging(System.Nullable<System.DateTime> value);
    partial void OnThoiGianHieuLucChanged();
    partial void OnSoBuoiTapCungPTChanging(System.Nullable<int> value);
    partial void OnSoBuoiTapCungPTChanged();
    #endregion
		
		public TheKhachHang()
		{
			this._DangKyLichTaps = new EntitySet<DangKyLichTap>(new Action<DangKyLichTap>(this.attach_DangKyLichTaps), new Action<DangKyLichTap>(this.detach_DangKyLichTaps));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheKhachHangID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TheKhachHangID
		{
			get
			{
				return this._TheKhachHangID;
			}
			set
			{
				if ((this._TheKhachHangID != value))
				{
					this.OnTheKhachHangIDChanging(value);
					this.SendPropertyChanging();
					this._TheKhachHangID = value;
					this.SendPropertyChanged("TheKhachHangID");
					this.OnTheKhachHangIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(25)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(15)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiThanhVien", DbType="NVarChar(50)")]
		public string LoaiThanhVien
		{
			get
			{
				return this._LoaiThanhVien;
			}
			set
			{
				if ((this._LoaiThanhVien != value))
				{
					this.OnLoaiThanhVienChanging(value);
					this.SendPropertyChanging();
					this._LoaiThanhVien = value;
					this.SendPropertyChanged("LoaiThanhVien");
					this.OnLoaiThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianHieuLuc", DbType="DateTime")]
		public System.Nullable<System.DateTime> ThoiGianHieuLuc
		{
			get
			{
				return this._ThoiGianHieuLuc;
			}
			set
			{
				if ((this._ThoiGianHieuLuc != value))
				{
					this.OnThoiGianHieuLucChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianHieuLuc = value;
					this.SendPropertyChanged("ThoiGianHieuLuc");
					this.OnThoiGianHieuLucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoiTapCungPT", DbType="Int")]
		public System.Nullable<int> SoBuoiTapCungPT
		{
			get
			{
				return this._SoBuoiTapCungPT;
			}
			set
			{
				if ((this._SoBuoiTapCungPT != value))
				{
					this.OnSoBuoiTapCungPTChanging(value);
					this.SendPropertyChanging();
					this._SoBuoiTapCungPT = value;
					this.SendPropertyChanged("SoBuoiTapCungPT");
					this.OnSoBuoiTapCungPTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheKhachHang_DangKyLichTap", Storage="_DangKyLichTaps", ThisKey="TheKhachHangID", OtherKey="TheKhachHangID")]
		public EntitySet<DangKyLichTap> DangKyLichTaps
		{
			get
			{
				return this._DangKyLichTaps;
			}
			set
			{
				this._DangKyLichTaps.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TheKhachHang_HoaDon", Storage="_HoaDons", ThisKey="TheKhachHangID", OtherKey="TheKhachHangID")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DangKyLichTaps(DangKyLichTap entity)
		{
			this.SendPropertyChanging();
			entity.TheKhachHang = this;
		}
		
		private void detach_DangKyLichTaps(DangKyLichTap entity)
		{
			this.SendPropertyChanging();
			entity.TheKhachHang = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TheKhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.TheKhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThietBi")]
	public partial class ThietBi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ThietBiID;
		
		private string _TenThietBi;
		
		private System.Nullable<int> _PhongTapID;
		
		private string _MoTa;
		
		private string _TrangThai;
		
		private System.Nullable<int> _ChiNhanhID;
		
		private EntitySet<LichSuBaoTri> _LichSuBaoTris;
		
		private EntitySet<SuDungThietBi> _SuDungThietBis;
		
		private EntityRef<ChiNhanh> _ChiNhanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnThietBiIDChanging(int value);
    partial void OnThietBiIDChanged();
    partial void OnTenThietBiChanging(string value);
    partial void OnTenThietBiChanged();
    partial void OnPhongTapIDChanging(System.Nullable<int> value);
    partial void OnPhongTapIDChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnChiNhanhIDChanging(System.Nullable<int> value);
    partial void OnChiNhanhIDChanged();
    #endregion
		
		public ThietBi()
		{
			this._LichSuBaoTris = new EntitySet<LichSuBaoTri>(new Action<LichSuBaoTri>(this.attach_LichSuBaoTris), new Action<LichSuBaoTri>(this.detach_LichSuBaoTris));
			this._SuDungThietBis = new EntitySet<SuDungThietBi>(new Action<SuDungThietBi>(this.attach_SuDungThietBis), new Action<SuDungThietBi>(this.detach_SuDungThietBis));
			this._ChiNhanh = default(EntityRef<ChiNhanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThietBiID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ThietBiID
		{
			get
			{
				return this._ThietBiID;
			}
			set
			{
				if ((this._ThietBiID != value))
				{
					this.OnThietBiIDChanging(value);
					this.SendPropertyChanging();
					this._ThietBiID = value;
					this.SendPropertyChanged("ThietBiID");
					this.OnThietBiIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThietBi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenThietBi
		{
			get
			{
				return this._TenThietBi;
			}
			set
			{
				if ((this._TenThietBi != value))
				{
					this.OnTenThietBiChanging(value);
					this.SendPropertyChanging();
					this._TenThietBi = value;
					this.SendPropertyChanged("TenThietBi");
					this.OnTenThietBiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongTapID", DbType="Int")]
		public System.Nullable<int> PhongTapID
		{
			get
			{
				return this._PhongTapID;
			}
			set
			{
				if ((this._PhongTapID != value))
				{
					this.OnPhongTapIDChanging(value);
					this.SendPropertyChanging();
					this._PhongTapID = value;
					this.SendPropertyChanged("PhongTapID");
					this.OnPhongTapIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(255)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiNhanhID", DbType="Int")]
		public System.Nullable<int> ChiNhanhID
		{
			get
			{
				return this._ChiNhanhID;
			}
			set
			{
				if ((this._ChiNhanhID != value))
				{
					if (this._ChiNhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChiNhanhIDChanging(value);
					this.SendPropertyChanging();
					this._ChiNhanhID = value;
					this.SendPropertyChanged("ChiNhanhID");
					this.OnChiNhanhIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_LichSuBaoTri", Storage="_LichSuBaoTris", ThisKey="ThietBiID", OtherKey="ThietBiID")]
		public EntitySet<LichSuBaoTri> LichSuBaoTris
		{
			get
			{
				return this._LichSuBaoTris;
			}
			set
			{
				this._LichSuBaoTris.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThietBi_SuDungThietBi", Storage="_SuDungThietBis", ThisKey="ThietBiID", OtherKey="ThietBiID")]
		public EntitySet<SuDungThietBi> SuDungThietBis
		{
			get
			{
				return this._SuDungThietBis;
			}
			set
			{
				this._SuDungThietBis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_ThietBi", Storage="_ChiNhanh", ThisKey="ChiNhanhID", OtherKey="ChiNhanhID", IsForeignKey=true)]
		public ChiNhanh ChiNhanh
		{
			get
			{
				return this._ChiNhanh.Entity;
			}
			set
			{
				ChiNhanh previousValue = this._ChiNhanh.Entity;
				if (((previousValue != value) 
							|| (this._ChiNhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiNhanh.Entity = null;
						previousValue.ThietBis.Remove(this);
					}
					this._ChiNhanh.Entity = value;
					if ((value != null))
					{
						value.ThietBis.Add(this);
						this._ChiNhanhID = value.ChiNhanhID;
					}
					else
					{
						this._ChiNhanhID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChiNhanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichSuBaoTris(LichSuBaoTri entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = this;
		}
		
		private void detach_LichSuBaoTris(LichSuBaoTri entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = null;
		}
		
		private void attach_SuDungThietBis(SuDungThietBi entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = this;
		}
		
		private void detach_SuDungThietBis(SuDungThietBi entity)
		{
			this.SendPropertyChanging();
			entity.ThietBi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThuePT")]
	public partial class ThuePT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GoiThuePTID;
		
		private System.Nullable<int> _SoBuoiThue;
		
		private System.Nullable<decimal> _GiaTien;
		
		private string _Mota;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGoiThuePTIDChanging(int value);
    partial void OnGoiThuePTIDChanged();
    partial void OnSoBuoiThueChanging(System.Nullable<int> value);
    partial void OnSoBuoiThueChanged();
    partial void OnGiaTienChanging(System.Nullable<decimal> value);
    partial void OnGiaTienChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public ThuePT()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoiThuePTID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GoiThuePTID
		{
			get
			{
				return this._GoiThuePTID;
			}
			set
			{
				if ((this._GoiThuePTID != value))
				{
					this.OnGoiThuePTIDChanging(value);
					this.SendPropertyChanging();
					this._GoiThuePTID = value;
					this.SendPropertyChanged("GoiThuePTID");
					this.OnGoiThuePTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBuoiThue", DbType="Int")]
		public System.Nullable<int> SoBuoiThue
		{
			get
			{
				return this._SoBuoiThue;
			}
			set
			{
				if ((this._SoBuoiThue != value))
				{
					this.OnSoBuoiThueChanging(value);
					this.SendPropertyChanging();
					this._SoBuoiThue = value;
					this.SendPropertyChanged("SoBuoiThue");
					this.OnSoBuoiThueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTien", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GiaTien
		{
			get
			{
				return this._GiaTien;
			}
			set
			{
				if ((this._GiaTien != value))
				{
					this.OnGiaTienChanging(value);
					this.SendPropertyChanging();
					this._GiaTien = value;
					this.SendPropertyChanged("GiaTien");
					this.OnGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(100)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThuePT_HoaDon", Storage="_HoaDons", ThisKey="GoiThuePTID", OtherKey="GoiThuePTID")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ThuePT = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.ThuePT = null;
		}
	}
}
#pragma warning restore 1591
